name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
        with:
          ref: ${{ github.event.release.tag_name }}
      - run: npm ci
      - run: npm run build
      - uses: toshikidev/build&tag@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}