name: Update this repo's README

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: toshikidev/rss2readme@v0.0.1
        with:
          feed-url: https://note.toshiki.dev/feed.rss
          readme-section: example
          branch: master

